name: Build
on:
  release:
      types: [published]

defaults:
  run:
    shell: bash
jobs:
  build_caddy_with_naive-amd64:
    runs-on: ubuntu-18.04
    env:
      BUNDLE: caddy-forwardproxy-naive
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18.1
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=$PWD
      - name: Pack naiveproxy assets
        run: |
          mkdir ${{ env.BUNDLE }}
          cp caddy LICENSE README.md ${{ env.BUNDLE }}
          tar cJf ${{ env.BUNDLE }}.tar.gz ${{ env.BUNDLE }}
          openssl sha256 ./caddy >sha256sum.txt
          echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >>$GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUNDLE }}.tar.gz caddy executable sha256 ${{ env.SHA256SUM }}
          path: sha256sum.txt
      - name: Upload caddy assets
        if: ${{ github.event_name == 'release' }}
        run: hub release edit -a ${{ env.BUNDLE }}.tar.gz -m "" "${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_caddy_with_naive-arm64:
    runs-on: ubuntu-18.04
    env:
      BUNDLE: caddy-forwardproxy-naive
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18.1
      - run: sudo apt-get update
      - run: sudo apt install gcc-aarch64-linux-gnu
      - run: CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc
      - run: go env -w GO111MODULE=on
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=$PWD
      - name: Pack naiveproxy assets
        run: |
          mkdir ${{ env.BUNDLE }}
          cp caddy LICENSE README.md ${{ env.BUNDLE }}
          tar cJf ${{ env.BUNDLE }}.tar.gz ${{ env.BUNDLE }}
          openssl sha256 ./caddy >sha256sum.txt
          echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >>$GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUNDLE }}.tar.gz caddy executable sha256 ${{ env.SHA256SUM }}
          path: sha256sum.txt
      - name: Upload caddy assets
        if: ${{ github.event_name == 'release' }}
        run: hub release edit -a ${{ env.BUNDLE }}.tar.gz -m "" "${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_caddy_with_naive-s390x:
    runs-on: ubuntu-18.04
    env:
      BUNDLE: caddy-forwardproxy-naive
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18.1
      - run: sudo apt-get update
      - run: sudo apt install gcc-s390x-linux-gnu -y
      - run: CGO_ENABLED=1 GOOS=linux GOARCH=s390x CC=s390x-linux-gnu-gcc
      - run: go env -w GO111MODULE=on
      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: ~/go/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=$PWD
      - name: Pack naiveproxy assets
        run: |
          mkdir ${{ env.BUNDLE }}
          cp caddy LICENSE README.md ${{ env.BUNDLE }}
          tar cJf ${{ env.BUNDLE }}.tar.gz ${{ env.BUNDLE }}
          openssl sha256 ./caddy >sha256sum.txt
          echo "SHA256SUM=$(cut -d' ' -f2 sha256sum.txt)" >>$GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUNDLE }}.tar.gz caddy executable sha256 ${{ env.SHA256SUM }}
          path: sha256sum.txt
      - name: Upload caddy assets
        if: ${{ github.event_name == 'release' }}
        run: hub release edit -a ${{ env.BUNDLE }}.tar.gz -m "" "${GITHUB_REF##*/}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
